version: "3.4"

services:

  trains:
    container_name: trains
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/trains
      - node_modules:/trains/node_modules
    ports:
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
      - "19006:19006"
      - "19007:19007"
    environment:
      NODE_ENV: development
      EXPO_USE_DEV_SERVER: 1
      EXPO_DEVTOOLS_LISTEN_ADDRESS: 0.0.0.0
      REACT_NATIVE_PACKAGER_HOSTNAME: 86.12.244.214
    entrypoint: "expo start --tunnel"

volumes:
  node_modules:
